function material_database = database_import(workbookFile, sheetName, dataLines)
%IMPORTFILE1 Import data from a spreadsheet
%  material_database = IMPORTFILE1(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  material_database = IMPORTFILE1(FILE, SHEET) reads from the specified
%  worksheet.
%
%  material_database = IMPORTFILE1(FILE, SHEET, DATALINES) reads from
%  the specified worksheet for the specified row interval(s). Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  temizcorrected2S1 = importfile1("C:\Users\mark_\Box\TIA - Sustainability Lab\Model_Code\temiz-corrected2.xls", "CleanDatabase", [2, 59]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 02-Jun-2023 18:14:54

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 70];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 9);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":I" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["Material", "Xch", "XchUnit", "CExC", "CExCUnit", "LHV", "LHVUnit", "Energy", "EnergyUnit"];
opts.VariableTypes = ["string", "double", "string", "double", "string", "double", "string", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, "Material", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Material", "XchUnit", "CExCUnit", "LHVUnit", "EnergyUnit"], "EmptyFieldRule", "auto");

% Import the data
material_database = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":I" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    material_database = [material_database; tb]; %#ok<AGROW>
end

end